# Generated by Django 5.2.10 on 2026-02-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen del producto (recomendado 600x600px)', null=True, upload_to='products/', verbose_name='Imagen'),
        ),
    ]
