# Generated by Django 5.2.10 on 2026-02-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_document',
            field=models.CharField(blank=True, max_length=30, verbose_name='Documento de identidad'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, verbose_name='Método de pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('declined', 'Rechazado'), ('voided', 'Anulado'), ('error', 'Error')], default='pending', max_length=20, verbose_name='Estado de pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='wompi_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Wompi Transaction ID'),
        ),
    ]
