# Generated by Django 5.2.10 on 2026-02-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_customer_city_order_customer_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_country',
            field=models.CharField(blank=True, max_length=100, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_state',
            field=models.CharField(blank=True, max_length=100, verbose_name='Departamento'),
        ),
    ]
