# Generated by Django 5.2.10 on 2026-02-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_add_customer_country_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_doc_type',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('PA', 'Pasaporte'), ('NIT', 'NIT')], max_length=5, verbose_name='Tipo de documento'),
        ),
    ]
