# Generated by Django 5.2.10 on 2026-02-18 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_clientservice_billing_type_and_more'),
        ('store', '0005_add_customer_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_type',
            field=models.CharField(choices=[('product', 'Producto'), ('service', 'Servicio')], default='product', max_length=10, verbose_name='Tipo de item'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='services.service', verbose_name='Servicio'),
        ),
    ]
