from django.db import migrations


def update_all_descriptions(apps, schema_editor):
    Service = apps.get_model('services', 'Service')

    descriptions = {}

    descriptions['Landing Page'] = (
        "Convierte visitantes en clientes con una Landing Page "
        "profesional diseñada específicamente para maximizar "
        "conversiones. En Megadominio creamos páginas de aterrizaje "
        "que combinan copywriting persuasivo, diseño visual "
        "impactante y optimización técnica para que cada clic "
        "cuente.\n\n"
        "BENEFICIOS PARA TU NEGOCIO:\n\n"
        "• Tasa de conversión hasta 5x mayor que una página "
        "web genérica.\n"
        "• Mensaje enfocado en una sola acción: comprar, "
        "registrarse, agendar o cotizar.\n"
        "• Diseño responsive optimizado para móvil donde "
        "ocurre el 70% del tráfico.\n"
        "• Velocidad de carga inferior a 2 segundos para "
        "minimizar rebote.\n"
        "• A/B testing integrado para mejorar resultados "
        "continuamente.\n"
        "• Integración directa con Google Ads y Meta Ads "
        "para tracking de conversiones.\n\n"
        "QUÉ INCLUYE:\n\n"
        "• Análisis de tu oferta, audiencia y competencia.\n"
        "• Copywriting profesional orientado a conversión "
        "(headline, beneficios, prueba social, CTA).\n"
        "• Diseño UI/UX personalizado con tu identidad de "
        "marca.\n"
        "• Desarrollo responsive con HTML5, CSS3, JavaScript "
        "y Tailwind CSS.\n"
        "• Formulario de captura integrado con tu CRM o "
        "email marketing.\n"
        "• Botón de WhatsApp Business y click-to-call.\n"
        "• Configuración de Google Analytics 4, GTM y "
        "eventos de conversión.\n"
        "• Certificado SSL y optimización de velocidad.\n"
        "• SEO on-page: meta tags, Open Graph, Schema.org.\n"
        "• Pruebas cross-browser y cross-device.\n\n"
        "PROCESO:\n\n"
        "1. Briefing estratégico y análisis de oferta.\n"
        "2. Wireframe y estructura de contenido.\n"
        "3. Diseño visual y aprobación.\n"
        "4. Desarrollo, integración y QA.\n"
        "5. Lanzamiento y configuración de tracking.\n"
        "6. Optimización post-lanzamiento basada en datos.\n\n"
        "STACK: HTML5, Tailwind CSS, JavaScript, Django, "
        "PostgreSQL, Cloudflare CDN, Google Tag Manager.\n\n"
        "Palabras clave: landing page Colombia, página de "
        "aterrizaje, landing page de conversión, diseño de "
        "landing page, landing page para Google Ads."
    )

    descriptions['Sitio Web Corporativo'] = (
        "Proyecta la imagen profesional que tu empresa merece "
        "con un Sitio Web Corporativo de alto nivel. Diseñamos "
        "y desarrollamos sitios web que comunican confianza, "
        "autoridad y profesionalismo desde el primer segundo, "
        "con arquitectura pensada para posicionar en Google y "
        "convertir visitantes en oportunidades de negocio.\n\n"
        "BENEFICIOS PARA TU NEGOCIO:\n\n"
        "• Presencia digital que genera confianza inmediata "
        "en clientes potenciales.\n"
        "• Arquitectura de contenidos optimizada para SEO "
        "y navegación intuitiva.\n"
        "• Panel de administración para actualizar contenidos "
        "sin conocimientos técnicos.\n"
        "• Diseño adaptable a cualquier dispositivo con "
        "experiencia perfecta.\n"
        "• Integración con Google Analytics, Search Console "
        "y herramientas de marketing.\n"
        "• Velocidad de carga optimizada (Lighthouse 90+).\n"
        "• Escalable: crece con tu empresa sin reconstruir.\n\n"
        "QUÉ INCLUYE:\n\n"
        "• Hasta 10 páginas: Inicio, Nosotros, Servicios, "
        "Blog, Contacto, y más.\n"
        "• Diseño UI/UX personalizado con identidad de marca.\n"
        "• CMS para gestión autónoma de contenidos.\n"
        "• Formularios de contacto y cotización.\n"
        "• Mapa de ubicación y datos de contacto.\n"
        "• Blog integrado para estrategia de contenidos.\n"
        "• SEO técnico completo: sitemap, robots, schema, "
        "meta tags.\n"
        "• Certificado SSL, headers de seguridad.\n"
        "• Integración con redes sociales.\n"
        "• Capacitación para gestión del sitio.\n\n"
        "PROCESO:\n\n"
        "1. Reunión de descubrimiento y análisis de marca.\n"
        "2. Arquitectura de información y wireframes.\n"
        "3. Diseño visual y prototipos interactivos.\n"
        "4. Desarrollo frontend y backend.\n"
        "5. QA, optimización y pruebas.\n"
        "6. Lanzamiento y soporte post-entrega (30 días).\n\n"
        "STACK: Django, PostgreSQL, Tailwind CSS, JavaScript, "
        "Docker, Nginx, Cloudflare.\n\n"
        "Palabras clave: sitio web corporativo Colombia, "
        "página web empresarial, diseño web corporativo, "
        "desarrollo web profesional, web corporativa."
    )

    descriptions['E-commerce Básico'] = (
        "Lanza tu tienda virtual con nuestro servicio de "
        "E-commerce Básico: todo lo que necesitas para empezar "
        "a vender en línea de forma profesional y segura. "
        "Ideal para emprendedores y pequeñas empresas que "
        "quieren dar el salto al comercio electrónico.\n\n"
        "BENEFICIOS PARA TU NEGOCIO:\n\n"
        "• Canal de ventas 24/7 que no depende de horarios "
        "ni ubicación física.\n"
        "• Catálogo de hasta 100 productos con gestión "
        "autónoma.\n"
        "• Pasarela de pago segura (PayU, MercadoPago, "
        "Wompi).\n"
        "• Carrito de compras optimizado para reducir "
        "abandono.\n"
        "• Notificaciones automáticas de pedidos por email.\n"
        "• Panel de administración intuitivo para gestionar "
        "productos, pedidos e inventario.\n"
        "• Diseño responsive que funciona perfecto en "
        "móvil.\n\n"
        "QUÉ INCLUYE:\n\n"
        "• Diseño personalizado de tienda con tu marca.\n"
        "• Catálogo de productos con categorías, filtros "
        "y búsqueda.\n"
        "• Carrito de compras y checkout optimizado.\n"
        "• Integración con pasarela de pago colombiana.\n"
        "• Gestión de inventario básica.\n"
        "• Emails transaccionales (confirmación, envío).\n"
        "• SEO on-page para productos y categorías.\n"
        "• Certificado SSL y seguridad.\n"
        "• Capacitación para administrar la tienda.\n\n"
        "PROCESO:\n\n"
        "1. Análisis de productos y modelo de negocio.\n"
        "2. Diseño de tienda y experiencia de compra.\n"
        "3. Desarrollo e integración de pagos.\n"
        "4. Carga de catálogo inicial.\n"
        "5. Pruebas de compra y QA.\n"
        "6. Lanzamiento y capacitación.\n\n"
        "STACK: Django, PostgreSQL, Tailwind CSS, PayU/"
        "MercadoPago API, Cloudflare.\n\n"
        "Palabras clave: tienda virtual Colombia, e-commerce "
        "básico, crear tienda en línea, vender por internet "
        "Colombia, tienda online económica."
    )

    descriptions['E-commerce Profesional'] = (
        "Escala tus ventas online con un E-commerce Profesional "
        "de alto rendimiento. Diseñado para empresas que "
        "necesitan funcionalidades avanzadas: catálogos "
        "extensos, múltiples pasarelas de pago, integraciones "
        "con ERP/inventario y estrategias de conversión "
        "sofisticadas.\n\n"
        "BENEFICIOS PARA TU NEGOCIO:\n\n"
        "• Catálogo ilimitado con variantes, atributos y "
        "filtros avanzados.\n"
        "• Múltiples pasarelas de pago y métodos (tarjeta, "
        "PSE, efectivo, contra-entrega).\n"
        "• Integración con sistemas de inventario, "
        "contabilidad y logística.\n"
        "• Recuperación automática de carritos abandonados.\n"
        "• Cupones, descuentos y programas de fidelización.\n"
        "• Dashboard de ventas con métricas en tiempo real.\n"
        "• Velocidad optimizada para catálogos grandes.\n\n"
        "QUÉ INCLUYE:\n\n"
        "• Todo lo del E-commerce Básico, más:\n"
        "• Catálogo ilimitado con variantes y atributos.\n"
        "• Múltiples pasarelas de pago integradas.\n"
        "• Sistema de cupones y promociones.\n"
        "• Recuperación de carritos por email automático.\n"
        "• Integración con ERP/contabilidad (Siigo, "
        "World Office).\n"
        "• Integración con transportadoras (Servientrega, "
        "Coordinadora, Envia).\n"
        "• Cálculo automático de envío por peso/destino.\n"
        "• Reseñas y valoraciones de productos.\n"
        "• Wishlist y comparador de productos.\n"
        "• SEO avanzado para productos con Schema Product.\n"
        "• Google Shopping y catálogo de Facebook.\n"
        "• Analytics de e-commerce mejorado (GA4).\n\n"
        "PROCESO:\n\n"
        "1. Análisis de negocio y requerimientos avanzados.\n"
        "2. Arquitectura técnica y diseño UX de compra.\n"
        "3. Desarrollo e integraciones con terceros.\n"
        "4. Migración de catálogo y datos.\n"
        "5. QA exhaustivo con pruebas de carga.\n"
        "6. Lanzamiento, monitoreo y optimización.\n\n"
        "STACK: Django, DRF, PostgreSQL, Redis, Celery, "
        "APIs de pago y logística, Docker, CI/CD.\n\n"
        "Palabras clave: tienda virtual profesional Colombia, "
        "e-commerce avanzado, plataforma de ventas online, "
        "desarrollo e-commerce, tienda virtual con ERP."
    )

    descriptions['Blog / Portal de Noticias'] = (
        "Posiciona tu marca como referente en tu industria "
        "con un Blog o Portal de Noticias profesional. "
        "Creamos plataformas de contenido optimizadas para "
        "SEO que atraen tráfico orgánico, generan autoridad "
        "y convierten lectores en clientes.\n\n"
        "BENEFICIOS PARA TU NEGOCIO:\n\n"
        "• Tráfico orgánico compuesto que crece mes a mes.\n"
        "• Posicionamiento como experto en tu sector.\n"
        "• Generación de leads a través de contenido de "
        "valor.\n"
        "• Base para estrategia de email marketing y redes "
        "sociales.\n"
        "• Mejora del SEO general de tu dominio.\n"
        "• Contenido evergreen que trabaja para ti 24/7.\n\n"
        "QUÉ INCLUYE:\n\n"
        "• Diseño personalizado del blog con tu marca.\n"
        "• CMS intuitivo para publicar sin conocimientos "
        "técnicos.\n"
        "• Categorías, etiquetas y sistema de búsqueda.\n"
        "• Artículos con formato rico: imágenes, videos, "
        "tablas, CTAs.\n"
        "• Sistema de comentarios moderados.\n"
        "• Suscripción por email (newsletter).\n"
        "• Compartir en redes sociales integrado.\n"
        "• SEO técnico: sitemap, schema Article, "
        "breadcrumbs.\n"
        "• Optimización de imágenes automática.\n"
        "• Páginas de autor con bio y enlaces.\n\n"
        "PROCESO:\n\n"
        "1. Definición de estrategia editorial.\n"
        "2. Diseño y arquitectura del blog.\n"
        "3. Desarrollo e integración con CMS.\n"
        "4. Configuración SEO y analytics.\n"
        "5. Capacitación editorial.\n"
        "6. Publicación de primeros artículos piloto.\n\n"
        "STACK: Django, PostgreSQL, Tailwind CSS, "
        "Cloudflare, GA4.\n\n"
        "Palabras clave: blog corporativo Colombia, portal "
        "de noticias, blog empresarial, marketing de "
        "contenidos, blog SEO optimizado."
    )

    descriptions['Portal Web Avanzado'] = (
        "Desarrollamos Portales Web Avanzados con "
        "funcionalidades complejas: áreas de usuario, "
        "dashboards, integraciones con APIs externas, "
        "flujos de trabajo personalizados y arquitectura "
        "escalable para soportar miles de usuarios "
        "concurrentes.\n\n"
        "BENEFICIOS PARA TU NEGOCIO:\n\n"
        "• Plataforma a medida que se adapta a tus "
        "procesos, no al revés.\n"
        "• Áreas privadas con roles y permisos "
        "granulares.\n"
        "• Dashboards con métricas en tiempo real.\n"
        "• Integraciones con cualquier sistema externo "
        "vía API.\n"
        "• Arquitectura escalable que soporta crecimiento.\n"
        "• Seguridad empresarial con auditoría de "
        "accesos.\n\n"
        "QUÉ INCLUYE:\n\n"
        "• Análisis de requerimientos y casos de uso.\n"
        "• Diseño UX/UI con prototipos interactivos.\n"
        "• Sistema de autenticación con roles y permisos.\n"
        "• Paneles de administración personalizados.\n"
        "• API REST para integraciones.\n"
        "• Notificaciones por email y en plataforma.\n"
        "• Reportes y exportación de datos.\n"
        "• Pruebas automatizadas y documentación.\n"
        "• Despliegue con CI/CD y monitoreo.\n"
        "• Soporte y mantenimiento post-lanzamiento.\n\n"
        "PROCESO:\n\n"
        "1. Levantamiento de requerimientos detallado.\n"
        "2. Arquitectura técnica y diseño de BD.\n"
        "3. Desarrollo iterativo con sprints.\n"
        "4. QA y pruebas de carga.\n"
        "5. Despliegue y migración de datos.\n"
        "6. Soporte continuo y evolución.\n\n"
        "STACK: Django, DRF, PostgreSQL, Redis, Celery, "
        "React/Next.js, Docker, AWS/DigitalOcean.\n\n"
        "Palabras clave: portal web avanzado Colombia, "
        "desarrollo de plataformas web, aplicación web "
        "a medida, portal con login, desarrollo web "
        "empresarial."
    )

    descriptions['Sistema a Medida'] = (
        "Desarrollamos Sistemas a Medida que digitalizan y "
        "optimizan los procesos únicos de tu empresa. Desde "
        "CRMs personalizados hasta sistemas de gestión "
        "internos, creamos software que se adapta "
        "perfectamente a tu operación.\n\n"
        "BENEFICIOS PARA TU NEGOCIO:\n\n"
        "• Software que refleja exactamente tus procesos "
        "y reglas de negocio.\n"
        "• Eliminación de hojas de cálculo y procesos "
        "manuales.\n"
        "• Control total sobre funcionalidades y "
        "evolución.\n"
        "• Integración con tus herramientas existentes.\n"
        "• Propiedad total del código fuente.\n"
        "• Escalabilidad sin límites de licencias.\n\n"
        "QUÉ INCLUYE:\n\n"
        "• Análisis de procesos y requerimientos.\n"
        "• Diseño de base de datos y arquitectura.\n"
        "• Desarrollo backend con Django y DRF.\n"
        "• Frontend moderno y responsive.\n"
        "• API REST documentada.\n"
        "• Roles, permisos y auditoría.\n"
        "• Reportes y dashboards.\n"
        "• Pruebas automatizadas.\n"
        "• Documentación técnica y de usuario.\n"
        "• Despliegue y capacitación.\n\n"
        "PROCESO:\n\n"
        "1. Discovery y mapeo de procesos.\n"
        "2. Especificación funcional y técnica.\n"
        "3. Desarrollo iterativo (sprints de 2 semanas).\n"
        "4. Demos y feedback continuo.\n"
        "5. QA, pruebas de aceptación.\n"
        "6. Despliegue, migración y soporte.\n\n"
        "STACK: Python, Django, DRF, PostgreSQL, Redis, "
        "Celery, React, Docker, CI/CD.\n\n"
        "Palabras clave: desarrollo de software a medida "
        "Colombia, sistema personalizado, software "
        "empresarial, CRM personalizado, desarrollo de "
        "aplicaciones empresariales."
    )

    descriptions['Hosting Básico'] = (
        "Alojamiento web confiable y económico para sitios "
        "pequeños y medianos. Nuestro Hosting Básico incluye "
        "todo lo necesario para mantener tu sitio en línea "
        "con buen rendimiento, seguridad y soporte técnico "
        "especializado.\n\n"
        "BENEFICIOS:\n\n"
        "• Uptime garantizado del 99.9%.\n"
        "• Soporte técnico en español por expertos.\n"
        "• Panel de control intuitivo.\n"
        "• Backups automáticos diarios.\n"
        "• Certificado SSL incluido.\n"
        "• Protección anti-DDoS básica.\n\n"
        "QUÉ INCLUYE:\n\n"
        "• 10 GB SSD de almacenamiento.\n"
        "• Ancho de banda ilimitado.\n"
        "• Hasta 5 cuentas de correo.\n"
        "• Certificado SSL Let's Encrypt.\n"
        "• Backup diario automático.\n"
        "• Panel de administración.\n"
        "• Soporte por ticket y email.\n"
        "• Monitoreo de uptime 24/7.\n\n"
        "Ideal para: landing pages, sitios corporativos "
        "pequeños, blogs personales.\n\n"
        "Palabras clave: hosting Colombia, alojamiento web "
        "económico, hosting básico, hosting con SSL, "
        "hosting para páginas web."
    )

    descriptions['Hosting Profesional'] = (
        "Hosting de alto rendimiento para sitios web con "
        "tráfico moderado a alto. Incluye recursos dedicados, "
        "caché avanzado, CDN y soporte prioritario para "
        "garantizar velocidad y estabilidad.\n\n"
        "BENEFICIOS:\n\n"
        "• Recursos dedicados (no compartidos).\n"
        "• Velocidad superior con caché de aplicación.\n"
        "• CDN global para carga rápida desde cualquier "
        "ubicación.\n"
        "• Soporte prioritario con tiempos de respuesta "
        "garantizados.\n"
        "• Escalabilidad vertical sin migración.\n"
        "• Staging environment incluido.\n\n"
        "QUÉ INCLUYE:\n\n"
        "• 50 GB SSD NVMe de almacenamiento.\n"
        "• 4 GB RAM dedicada.\n"
        "• Ancho de banda ilimitado.\n"
        "• Hasta 25 cuentas de correo.\n"
        "• Certificado SSL premium.\n"
        "• CDN con Cloudflare Pro.\n"
        "• Caché de aplicación (Redis/Varnish).\n"
        "• Backups diarios con retención de 30 días.\n"
        "• Ambiente de staging.\n"
        "• Soporte prioritario 24/7.\n"
        "• Monitoreo avanzado con alertas.\n\n"
        "Ideal para: e-commerce, portales con tráfico, "
        "aplicaciones web.\n\n"
        "Palabras clave: hosting profesional Colombia, "
        "hosting de alto rendimiento, hosting con CDN, "
        "hosting para e-commerce, alojamiento web "
        "profesional."
    )

    descriptions['Hosting Premium'] = (
        "La solución de hosting más completa para empresas "
        "que exigen máximo rendimiento, seguridad y "
        "disponibilidad. Infraestructura dedicada con "
        "administración completa por nuestro equipo de "
        "DevOps.\n\n"
        "BENEFICIOS:\n\n"
        "• Infraestructura dedicada y administrada.\n"
        "• Rendimiento máximo con SSD NVMe y RAM "
        "dedicada.\n"
        "• Seguridad empresarial: WAF, IDS, hardening.\n"
        "• Administración completa por equipo DevOps.\n"
        "• SLA con 99.99% de uptime.\n"
        "• Escalabilidad horizontal y vertical.\n\n"
        "QUÉ INCLUYE:\n\n"
        "• 200 GB SSD NVMe.\n"
        "• 16 GB RAM dedicada.\n"
        "• CPU dedicada (4 cores).\n"
        "• Ancho de banda ilimitado.\n"
        "• Cuentas de correo ilimitadas.\n"
        "• SSL Wildcard.\n"
        "• CDN Enterprise.\n"
        "• WAF y protección DDoS avanzada.\n"
        "• Backups cada 6 horas, retención 90 días.\n"
        "• Monitoreo 24/7 con respuesta proactiva.\n"
        "• Administración completa del servidor.\n"
        "• Soporte VIP con respuesta en menos de 1 hora.\n\n"
        "Ideal para: empresas con alto tráfico, "
        "aplicaciones críticas, e-commerce de alto "
        "volumen.\n\n"
        "Palabras clave: hosting premium Colombia, hosting "
        "administrado, hosting empresarial, servidor "
        "dedicado, hosting de alto tráfico."
    )

    descriptions['Servidor VPS'] = (
        "Servidor Virtual Privado (VPS) con recursos "
        "garantizados y control total. Ideal para proyectos "
        "que necesitan configuraciones personalizadas, "
        "múltiples aplicaciones o entornos de desarrollo "
        "dedicados.\n\n"
        "BENEFICIOS:\n\n"
        "• Recursos 100% dedicados y garantizados.\n"
        "• Acceso root completo para configuración "
        "personalizada.\n"
        "• Aislamiento total de otros usuarios.\n"
        "• Múltiples aplicaciones en un solo servidor.\n"
        "• Snapshots y restauración instantánea.\n"
        "• Escalabilidad bajo demanda.\n\n"
        "QUÉ INCLUYE:\n\n"
        "• VPS con SSD NVMe (desde 40 GB).\n"
        "• RAM dedicada (desde 2 GB).\n"
        "• CPU dedicada (desde 2 cores).\n"
        "• IP dedicada.\n"
        "• Acceso root/SSH.\n"
        "• Panel de control (opcional).\n"
        "• Backups semanales.\n"
        "• Monitoreo de recursos.\n"
        "• Soporte técnico especializado.\n"
        "• Opción de administración completa.\n\n"
        "Ideal para: desarrolladores, agencias, múltiples "
        "sitios, aplicaciones personalizadas.\n\n"
        "Palabras clave: servidor VPS Colombia, VPS "
        "administrado, servidor virtual, VPS con SSD, "
        "hosting VPS Colombia."
    )

    descriptions['Registro de Dominio'] = (
        "Asegura tu presencia en internet con un dominio "
        "profesional. Gestionamos el registro, configuración "
        "DNS y renovación de tu dominio para que nunca "
        "pierdas tu identidad digital.\n\n"
        "BENEFICIOS:\n\n"
        "• Protección de tu marca en internet.\n"
        "• Configuración DNS profesional y segura.\n"
        "• Renovación automática para evitar pérdidas.\n"
        "• Privacidad WHOIS incluida.\n"
        "• Soporte para múltiples extensiones (.com, "
        ".co, .net, .org, etc.).\n"
        "• Gestión centralizada de todos tus dominios.\n\n"
        "QUÉ INCLUYE:\n\n"
        "• Registro del dominio por 1 año.\n"
        "• Configuración DNS completa.\n"
        "• Registros SPF, DKIM y DMARC para email.\n"
        "• Privacidad WHOIS.\n"
        "• Panel de gestión de DNS.\n"
        "• Recordatorio de renovación.\n"
        "• Soporte para transferencias.\n"
        "• Asesoría en selección de dominio.\n\n"
        "Palabras clave: registro de dominio Colombia, "
        "comprar dominio .co, dominio web, nombre de "
        "dominio, registrar dominio."
    )

    descriptions['Mantenimiento Web Básico'] = (
        "Mantén tu sitio web seguro, actualizado y "
        "funcionando perfectamente con nuestro plan de "
        "Mantenimiento Web Básico. Nos encargamos de las "
        "actualizaciones, backups y monitoreo para que tú "
        "te enfoques en tu negocio.\n\n"
        "BENEFICIOS:\n\n"
        "• Sitio siempre actualizado y seguro.\n"
        "• Prevención de problemas antes de que ocurran.\n"
        "• Backups regulares para recuperación rápida.\n"
        "• Monitoreo de uptime y rendimiento.\n"
        "• Soporte técnico cuando lo necesites.\n"
        "• Tranquilidad total sobre tu presencia web.\n\n"
        "QUÉ INCLUYE:\n\n"
        "• Actualizaciones de seguridad mensuales.\n"
        "• Backup semanal del sitio y base de datos.\n"
        "• Monitoreo de uptime 24/7.\n"
        "• Revisión de rendimiento mensual.\n"
        "• Corrección de errores menores (hasta 2 horas "
        "al mes).\n"
        "• Reporte mensual de estado del sitio.\n"
        "• Soporte por email con respuesta en 24 horas.\n"
        "• Renovación de certificado SSL.\n\n"
        "Ideal para: sitios corporativos, landing pages, "
        "blogs.\n\n"
        "Palabras clave: mantenimiento web Colombia, "
        "soporte web, mantenimiento de página web, "
        "actualización de sitio web, mantenimiento "
        "WordPress."
    )

    descriptions['Mantenimiento Web Premium'] = (
        "Servicio de Mantenimiento Web Premium con soporte "
        "prioritario, optimización continua y horas de "
        "desarrollo incluidas. Para empresas que necesitan "
        "su sitio web siempre en óptimas condiciones y en "
        "constante evolución.\n\n"
        "BENEFICIOS:\n\n"
        "• Soporte prioritario con respuesta en menos de "
        "4 horas.\n"
        "• Horas de desarrollo incluidas para mejoras.\n"
        "• Optimización continua de velocidad y SEO.\n"
        "• Monitoreo proactivo con alertas inmediatas.\n"
        "• Backups diarios con restauración garantizada.\n"
        "• Informes detallados de rendimiento y seguridad.\n\n"
        "QUÉ INCLUYE:\n\n"
        "• Todo lo del plan Básico, más:\n"
        "• Actualizaciones semanales de seguridad.\n"
        "• Backup diario con retención de 30 días.\n"
        "• 5 horas de desarrollo/mejoras al mes.\n"
        "• Optimización de velocidad trimestral.\n"
        "• Revisión SEO técnico mensual.\n"
        "• Monitoreo de seguridad con escaneo de "
        "vulnerabilidades.\n"
        "• Soporte prioritario por email, chat y "
        "teléfono.\n"
        "• Reporte semanal de estado.\n"
        "• Reunión mensual de revisión.\n"
        "• Gestor de cuenta dedicado.\n\n"
        "Ideal para: e-commerce, portales con tráfico, "
        "sitios críticos para el negocio.\n\n"
        "Palabras clave: mantenimiento web premium "
        "Colombia, soporte web prioritario, mantenimiento "
        "web empresarial, soporte técnico web, "
        "administración de sitio web."
    )

    descriptions['Migración de Sitio Web'] = (
        "Migra tu sitio web a una mejor plataforma o "
        "servidor sin perder posicionamiento, datos ni "
        "funcionalidad. Nuestro servicio de Migración "
        "garantiza una transición segura con cero o "
        "mínima interrupción.\n\n"
        "BENEFICIOS:\n\n"
        "• Cero pérdida de datos ni contenido.\n"
        "• Preservación del posicionamiento SEO.\n"
        "• Mínima o nula interrupción del servicio.\n"
        "• Mejora de rendimiento en la nueva plataforma.\n"
        "• Plan de rollback en caso de contingencia.\n"
        "• Verificación exhaustiva post-migración.\n\n"
        "QUÉ INCLUYE:\n\n"
        "• Auditoría del sitio actual y plan de "
        "migración.\n"
        "• Backup completo pre-migración.\n"
        "• Migración de archivos, base de datos y "
        "configuraciones.\n"
        "• Redirecciones 301 para preservar SEO.\n"
        "• Configuración DNS y propagación.\n"
        "• Pruebas funcionales completas.\n"
        "• Verificación de enlaces y recursos.\n"
        "• Monitoreo post-migración (72 horas).\n"
        "• Documentación del proceso.\n\n"
        "PROCESO:\n\n"
        "1. Auditoría y plan de migración.\n"
        "2. Preparación del entorno destino.\n"
        "3. Migración en ambiente de staging.\n"
        "4. Verificación y pruebas.\n"
        "5. Cutover DNS en horario de bajo tráfico.\n"
        "6. Monitoreo intensivo post-migración.\n\n"
        "Palabras clave: migración web Colombia, migrar "
        "sitio web, cambio de hosting, migración de "
        "servidor, transferir página web."
    )

    descriptions['Seguridad Web Avanzada'] = (
        "Protege tu sitio web y los datos de tus clientes "
        "con nuestro servicio de Seguridad Web Avanzada. "
        "Implementamos múltiples capas de protección para "
        "prevenir ataques, detectar vulnerabilidades y "
        "responder ante incidentes.\n\n"
        "BENEFICIOS:\n\n"
        "• Protección contra las principales amenazas web "
        "(OWASP Top 10).\n"
        "• Detección temprana de vulnerabilidades.\n"
        "• Confianza del usuario al navegar tu sitio.\n"
        "• Cumplimiento de normativas de protección de "
        "datos.\n"
        "• Respuesta rápida ante incidentes de seguridad.\n"
        "• Mejor posicionamiento (Google premia sitios "
        "seguros).\n\n"
        "QUÉ INCLUYE:\n\n"
        "• Auditoría de seguridad completa.\n"
        "• Implementación de WAF (Web Application "
        "Firewall).\n"
        "• Certificado SSL/TLS premium.\n"
        "• Headers de seguridad (CSP, HSTS, X-Frame, "
        "X-XSS).\n"
        "• Escaneo de vulnerabilidades periódico.\n"
        "• Protección anti-DDoS.\n"
        "• Hardening del servidor.\n"
        "• Monitoreo de integridad de archivos.\n"
        "• Plan de respuesta a incidentes.\n"
        "• Backups cifrados.\n"
        "• Reporte mensual de seguridad.\n\n"
        "Palabras clave: seguridad web Colombia, "
        "protección de sitio web, WAF, auditoría de "
        "seguridad web, seguridad informática, "
        "ciberseguridad web."
    )

    descriptions['Auditoría Web Completa'] = (
        "Obtén un diagnóstico completo del estado de tu "
        "sitio web con nuestra Auditoría Web. Analizamos "
        "rendimiento, SEO, seguridad, accesibilidad y "
        "experiencia de usuario para entregarte un plan "
        "de acción priorizado.\n\n"
        "BENEFICIOS:\n\n"
        "• Visión 360° del estado real de tu sitio.\n"
        "• Identificación de problemas ocultos que "
        "afectan rendimiento y SEO.\n"
        "• Plan de acción priorizado por impacto.\n"
        "• Benchmark contra competidores.\n"
        "• Base sólida para tomar decisiones de "
        "inversión.\n"
        "• Métricas claras de antes y después.\n\n"
        "QUÉ INCLUYE:\n\n"
        "• Auditoría de rendimiento (Core Web Vitals, "
        "Lighthouse).\n"
        "• Auditoría SEO técnico (indexación, rastreo, "
        "errores).\n"
        "• Auditoría de contenido y keywords.\n"
        "• Auditoría de seguridad (SSL, headers, "
        "vulnerabilidades).\n"
        "• Auditoría de accesibilidad (WCAG 2.1).\n"
        "• Auditoría de UX y conversión.\n"
        "• Análisis de competidores (3 competidores).\n"
        "• Documento de hallazgos (50+ páginas).\n"
        "• Plan de acción priorizado.\n"
        "• Presentación ejecutiva de resultados.\n"
        "• Sesión de Q&A con el equipo.\n\n"
        "HERRAMIENTAS: Screaming Frog, Ahrefs, "
        "Lighthouse, GTmetrix, OWASP ZAP, axe.\n\n"
        "Palabras clave: auditoría web Colombia, "
        "análisis de sitio web, auditoría SEO, "
        "auditoría de rendimiento web, diagnóstico "
        "web completo."
    )

    descriptions['Optimización de Velocidad'] = (
        "Acelera tu sitio web y mejora la experiencia de "
        "usuario con nuestro servicio de Optimización de "
        "Velocidad. Un sitio rápido convierte más, "
        "posiciona mejor y retiene más visitantes.\n\n"
        "BENEFICIOS:\n\n"
        "• Mejora de Core Web Vitals para ranking en "
        "Google.\n"
        "• Reducción de tasa de rebote hasta un 40%.\n"
        "• Mayor tasa de conversión (cada segundo "
        "cuenta).\n"
        "• Mejor experiencia en dispositivos móviles.\n"
        "• Menor consumo de recursos del servidor.\n"
        "• Lighthouse score 90+ garantizado.\n\n"
        "QUÉ INCLUYE:\n\n"
        "• Diagnóstico completo de rendimiento.\n"
        "• Optimización de imágenes (WebP/AVIF, lazy "
        "loading, responsive).\n"
        "• Minificación y compresión de CSS/JS.\n"
        "• Configuración de caché del navegador y "
        "servidor.\n"
        "• Implementación de CDN.\n"
        "• Optimización de fuentes web.\n"
        "• Eliminación de recursos que bloquean "
        "renderizado.\n"
        "• Optimización de base de datos.\n"
        "• Configuración de compresión Gzip/Brotli.\n"
        "• Reporte antes/después con métricas.\n\n"
        "Palabras clave: optimización de velocidad web "
        "Colombia, mejorar velocidad de carga, Core Web "
        "Vitals, optimización de rendimiento web, "
        "acelerar página web."
    )

    descriptions['Certificado SSL Premium'] = (
        "Protege la información de tus usuarios y mejora "
        "tu posicionamiento con un Certificado SSL Premium. "
        "Más que un candado verde: confianza, seguridad y "
        "mejor ranking en Google.\n\n"
        "BENEFICIOS:\n\n"
        "• Cifrado de datos entre usuario y servidor.\n"
        "• Confianza visual (candado en el navegador).\n"
        "• Mejor posicionamiento en Google (HTTPS es "
        "señal de ranking).\n"
        "• Cumplimiento de normativas de protección "
        "de datos.\n"
        "• Compatibilidad con todos los navegadores.\n"
        "• Garantía del certificado incluida.\n\n"
        "QUÉ INCLUYE:\n\n"
        "• Certificado SSL/TLS (DV, OV o EV según "
        "necesidad).\n"
        "• Instalación y configuración completa.\n"
        "• Redirección HTTP a HTTPS.\n"
        "• Configuración de HSTS.\n"
        "• Verificación de mixed content.\n"
        "• Renovación automática.\n"
        "• Monitoreo de expiración.\n"
        "• Soporte técnico incluido.\n\n"
        "Palabras clave: certificado SSL Colombia, "
        "SSL para página web, HTTPS, certificado de "
        "seguridad web, SSL premium."
    )

    descriptions['Backup Automático'] = (
        "Nunca pierdas tu información con nuestro servicio "
        "de Backup Automático. Copias de seguridad "
        "programadas, cifradas y almacenadas en múltiples "
        "ubicaciones para garantizar la continuidad de tu "
        "negocio.\n\n"
        "BENEFICIOS:\n\n"
        "• Protección contra pérdida de datos.\n"
        "• Recuperación rápida ante cualquier incidente.\n"
        "• Copias cifradas y almacenadas de forma segura.\n"
        "• Automatización total sin intervención manual.\n"
        "• Múltiples puntos de restauración.\n"
        "• Tranquilidad total sobre tus datos.\n\n"
        "QUÉ INCLUYE:\n\n"
        "• Backup automático programado (diario/semanal).\n"
        "• Copia de archivos y base de datos.\n"
        "• Cifrado AES-256 en reposo y tránsito.\n"
        "• Almacenamiento en ubicación remota.\n"
        "• Retención configurable (7-90 días).\n"
        "• Restauración bajo demanda.\n"
        "• Verificación automática de integridad.\n"
        "• Notificaciones de estado por email.\n"
        "• Reporte mensual de backups.\n\n"
        "Palabras clave: backup automático Colombia, "
        "copias de seguridad web, respaldo de datos, "
        "backup de sitio web, recuperación de datos."
    )

    descriptions['Email Corporativo Básico'] = (
        "Proyecta profesionalismo con correo electrónico "
        "con tu propio dominio (tu@tuempresa.com). Nuestro "
        "Email Corporativo Básico incluye todo lo necesario "
        "para comunicación empresarial confiable.\n\n"
        "BENEFICIOS:\n\n"
        "• Imagen profesional con tu dominio.\n"
        "• Mayor confianza de clientes y proveedores.\n"
        "• Mejor entregabilidad que correos gratuitos.\n"
        "• Antispam y antivirus incluidos.\n"
        "• Acceso desde cualquier dispositivo.\n"
        "• Soporte técnico especializado.\n\n"
        "QUÉ INCLUYE:\n\n"
        "• Hasta 5 cuentas de correo.\n"
        "• 10 GB de almacenamiento por cuenta.\n"
        "• Webmail responsive.\n"
        "• Configuración en Outlook, Gmail, móvil.\n"
        "• Antispam y antivirus.\n"
        "• Registros SPF, DKIM y DMARC.\n"
        "• Soporte por email.\n"
        "• Panel de administración.\n\n"
        "Palabras clave: correo corporativo Colombia, "
        "email empresarial, correo con dominio propio, "
        "email profesional, correo electrónico "
        "empresarial."
    )

    descriptions['Email Corporativo Empresarial'] = (
        "Solución de correo empresarial de alto nivel con "
        "almacenamiento amplio, herramientas de colaboración "
        "y seguridad avanzada. Ideal para equipos que "
        "necesitan productividad y control.\n\n"
        "BENEFICIOS:\n\n"
        "• Almacenamiento amplio para equipos grandes.\n"
        "• Herramientas de colaboración integradas.\n"
        "• Seguridad avanzada con MFA y DLP.\n"
        "• Administración centralizada de cuentas.\n"
        "• Archivado y cumplimiento normativo.\n"
        "• Migración sin interrupciones.\n\n"
        "QUÉ INCLUYE:\n\n"
        "• Cuentas ilimitadas de correo.\n"
        "• 50 GB de almacenamiento por cuenta.\n"
        "• Calendario y contactos compartidos.\n"
        "• Grupos de distribución y alias.\n"
        "• MFA (autenticación multifactor).\n"
        "• Políticas de retención y archivado.\n"
        "• DLP (prevención de pérdida de datos).\n"
        "• Migración completa desde proveedor anterior.\n"
        "• Panel de administración avanzado.\n"
        "• Soporte prioritario.\n\n"
        "Palabras clave: correo empresarial Colombia, "
        "email corporativo avanzado, correo electrónico "
        "empresarial, solución de email, correo con "
        "seguridad avanzada."
    )

    descriptions['Google Workspace'] = (
        "Potencia la productividad de tu equipo con Google "
        "Workspace (antes G Suite). Gmail profesional, "
        "Drive, Docs, Meet y más, todo integrado con tu "
        "dominio empresarial.\n\n"
        "BENEFICIOS:\n\n"
        "• Suite completa de productividad en la nube.\n"
        "• Colaboración en tiempo real con tu equipo.\n"
        "• 30 GB a almacenamiento ilimitado por usuario.\n"
        "• Videoconferencias con Google Meet.\n"
        "• Seguridad empresarial de Google.\n"
        "• Acceso desde cualquier dispositivo.\n\n"
        "QUÉ INCLUYE:\n\n"
        "• Configuración completa de Google Workspace.\n"
        "• Gmail con tu dominio.\n"
        "• Google Drive, Docs, Sheets, Slides.\n"
        "• Google Meet y Chat.\n"
        "• Google Calendar compartido.\n"
        "• Configuración DNS (MX, SPF, DKIM, DMARC).\n"
        "• Migración de correos existentes.\n"
        "• Capacitación para el equipo.\n"
        "• Administración de usuarios y políticas.\n"
        "• Soporte técnico continuo.\n\n"
        "Palabras clave: Google Workspace Colombia, "
        "G Suite, Gmail empresarial, correo Google "
        "con dominio, productividad en la nube."
    )

    descriptions['Email Marketing'] = (
        "Conecta con tu audiencia y genera ventas "
        "recurrentes con campañas de Email Marketing "
        "profesionales. Diseñamos, automatizamos y "
        "optimizamos tus comunicaciones por correo para "
        "maximizar apertura, clics y conversiones.\n\n"
        "BENEFICIOS:\n\n"
        "• ROI promedio de $36 por cada $1 invertido.\n"
        "• Comunicación directa con tu audiencia.\n"
        "• Automatización de secuencias de venta.\n"
        "• Segmentación avanzada por comportamiento.\n"
        "• Métricas claras de rendimiento.\n"
        "• Fidelización y retención de clientes.\n\n"
        "QUÉ INCLUYE:\n\n"
        "• Estrategia de email marketing.\n"
        "• Configuración de plataforma (Mailchimp, "
        "ActiveCampaign o SendGrid).\n"
        "• Diseño de plantillas responsive con tu marca.\n"
        "• Segmentación de listas de contactos.\n"
        "• Automatizaciones: bienvenida, nurturing, "
        "carrito abandonado, post-venta.\n"
        "• Diseño y envío de campañas mensuales.\n"
        "• A/B testing de asuntos y contenido.\n"
        "• Reportes de rendimiento (apertura, clics, "
        "conversiones).\n"
        "• Limpieza y mantenimiento de listas.\n"
        "• Cumplimiento de normativas anti-spam.\n\n"
        "Palabras clave: email marketing Colombia, "
        "campañas de correo, automatización de email, "
        "newsletter empresarial, marketing por correo "
        "electrónico."
    )

    descriptions['Publicidad en Google Ads'] = (
        "Aparece en los primeros resultados de Google "
        "cuando tus clientes potenciales buscan lo que "
        "ofreces. Gestionamos tus campañas de Google Ads "
        "con enfoque en ROI y optimización continua.\n\n"
        "BENEFICIOS:\n\n"
        "• Visibilidad inmediata en Google.\n"
        "• Tráfico cualificado con intención de compra.\n"
        "• Control total del presupuesto.\n"
        "• Resultados medibles desde el día 1.\n"
        "• Optimización continua para reducir CPC.\n"
        "• Remarketing para recuperar visitantes.\n\n"
        "QUÉ INCLUYE:\n\n"
        "• Investigación de palabras clave.\n"
        "• Estructura de campañas optimizada.\n"
        "• Creación de anuncios (Search, Display, "
        "Shopping, YouTube).\n"
        "• Extensiones de anuncio configuradas.\n"
        "• Configuración de conversiones y remarketing.\n"
        "• Landing pages optimizadas (opcional).\n"
        "• Optimización semanal de pujas y anuncios.\n"
        "• Palabras clave negativas.\n"
        "• A/B testing de anuncios.\n"
        "• Reportes quincenales de rendimiento.\n"
        "• Reunión mensual de estrategia.\n\n"
        "Palabras clave: Google Ads Colombia, publicidad "
        "en Google, campañas SEM, agencia Google Ads, "
        "anuncios en Google, PPC Colombia."
    )

    descriptions['Publicidad en Facebook/Instagram'] = (
        "Llega a tu audiencia ideal en Facebook e Instagram "
        "con campañas publicitarias diseñadas para generar "
        "resultados. Segmentación precisa, creatividades "
        "que convierten y optimización basada en datos.\n\n"
        "BENEFICIOS:\n\n"
        "• Alcance masivo en las redes más usadas.\n"
        "• Segmentación por intereses, comportamiento "
        "y demografía.\n"
        "• Audiencias lookalike para escalar.\n"
        "• Formatos visuales de alto impacto.\n"
        "• Remarketing dinámico de productos.\n"
        "• Métricas detalladas de rendimiento.\n\n"
        "QUÉ INCLUYE:\n\n"
        "• Estrategia de campañas por objetivo.\n"
        "• Creación de audiencias personalizadas y "
        "lookalike.\n"
        "• Diseño de creatividades (imágenes, carruseles, "
        "videos).\n"
        "• Copywriting persuasivo para anuncios.\n"
        "• Configuración de Meta Pixel y Conversion API.\n"
        "• A/B testing de audiencias y creatividades.\n"
        "• Optimización diaria de campañas.\n"
        "• Remarketing y retargeting.\n"
        "• Reportes quincenales.\n"
        "• Reunión mensual de estrategia.\n\n"
        "Palabras clave: publicidad Facebook Colombia, "
        "anuncios Instagram, Meta Ads, publicidad en "
        "redes sociales, agencia de Facebook Ads."
    )

    descriptions['Gestión de Redes Sociales'] = (
        "Construye una comunidad activa y comprometida "
        "alrededor de tu marca con nuestra Gestión de "
        "Redes Sociales profesional. Contenido estratégico, "
        "diseño atractivo y análisis de resultados para "
        "crecer tu presencia digital.\n\n"
        "BENEFICIOS:\n\n"
        "• Presencia activa y profesional en redes.\n"
        "• Contenido alineado con tu estrategia de "
        "marca.\n"
        "• Crecimiento orgánico de seguidores.\n"
        "• Mayor engagement y reconocimiento.\n"
        "• Ahorro de tiempo para tu equipo.\n"
        "• Métricas claras de crecimiento.\n\n"
        "QUÉ INCLUYE:\n\n"
        "• Estrategia de contenidos mensual.\n"
        "• Calendario editorial.\n"
        "• Diseño de 12-20 publicaciones al mes.\n"
        "• Copywriting para cada publicación.\n"
        "• Stories y Reels (según plataforma).\n"
        "• Gestión de comunidad (respuesta a "
        "comentarios y mensajes).\n"
        "• Monitoreo de menciones y reputación.\n"
        "• Reporte mensual de métricas.\n"
        "• Reunión mensual de planificación.\n\n"
        "Plataformas: Facebook, Instagram, LinkedIn, "
        "TikTok, X (Twitter).\n\n"
        "Palabras clave: gestión de redes sociales "
        "Colombia, community manager, manejo de redes "
        "sociales, social media, agencia de redes "
        "sociales."
    )

    descriptions['Estrategia Digital Integral'] = (
        "Alinea todos tus canales digitales bajo una "
        "estrategia unificada que maximiza resultados. "
        "Nuestro servicio de Estrategia Digital Integral "
        "conecta SEO, pauta, contenido, redes sociales y "
        "email marketing en un plan coherente orientado "
        "a tus objetivos de negocio.\n\n"
        "BENEFICIOS:\n\n"
        "• Visión unificada de todos los canales.\n"
        "• Sinergia entre orgánico y pago.\n"
        "• KPIs claros y medibles por canal.\n"
        "• Optimización del presupuesto total.\n"
        "• Decisiones basadas en datos.\n"
        "• Crecimiento sostenible y predecible.\n\n"
        "QUÉ INCLUYE:\n\n"
        "• Diagnóstico de presencia digital actual.\n"
        "• Definición de buyer personas.\n"
        "• Estrategia por canal (SEO, SEM, Social, "
        "Email).\n"
        "• Plan de contenidos integrado.\n"
        "• Presupuesto optimizado por canal.\n"
        "• Calendario de ejecución trimestral.\n"
        "• KPIs y OKRs por canal.\n"
        "• Dashboard unificado de métricas.\n"
        "• Reuniones quincenales de seguimiento.\n"
        "• Ajustes mensuales basados en datos.\n\n"
        "Palabras clave: estrategia digital Colombia, "
        "plan de marketing digital, estrategia de "
        "marketing online, consultoría de marketing "
        "digital, plan digital integral."
    )

    descriptions['SEO Básico'] = (
        "Comienza a posicionar tu sitio web en Google con "
        "nuestro servicio de SEO Básico. Optimizaciones "
        "fundamentales que sientan las bases para un "
        "crecimiento orgánico sostenible.\n\n"
        "BENEFICIOS:\n\n"
        "• Mejora de visibilidad en buscadores.\n"
        "• Corrección de errores técnicos que frenan "
        "tu posicionamiento.\n"
        "• Optimización de las páginas más importantes.\n"
        "• Base sólida para estrategia SEO avanzada.\n"
        "• Tráfico orgánico creciente.\n"
        "• Reporte de evolución mensual.\n\n"
        "QUÉ INCLUYE:\n\n"
        "• Auditoría SEO técnica inicial.\n"
        "• Investigación de 20 palabras clave.\n"
        "• Optimización on-page de hasta 10 páginas.\n"
        "• Configuración de Google Search Console y "
        "Analytics.\n"
        "• Sitemap XML y robots.txt.\n"
        "• Corrección de errores de rastreo.\n"
        "• Meta títulos y descripciones optimizados.\n"
        "• Estructura de headings (H1-H3).\n"
        "• Datos estructurados básicos.\n"
        "• Reporte mensual de posiciones.\n\n"
        "Ideal para: sitios nuevos o que nunca han "
        "tenido SEO.\n\n"
        "Palabras clave: SEO básico Colombia, "
        "posicionamiento web, optimización SEO, "
        "SEO para principiantes, SEO económico."
    )

    descriptions['SEO Avanzado'] = (
        "Domina los resultados de búsqueda con nuestro "
        "servicio de SEO Avanzado. Estrategia completa "
        "que combina SEO técnico, contenido optimizado, "
        "link building y análisis competitivo para "
        "posicionar en keywords de alta competencia.\n\n"
        "BENEFICIOS:\n\n"
        "• Posicionamiento en keywords competitivas.\n"
        "• Tráfico orgánico de alta calidad.\n"
        "• Autoridad de dominio creciente.\n"
        "• Rich snippets y featured snippets.\n"
        "• Ventaja competitiva sostenible.\n"
        "• ROI compuesto mes a mes.\n\n"
        "QUÉ INCLUYE:\n\n"
        "• Todo lo del SEO Básico, más:\n"
        "• Investigación de 100+ palabras clave.\n"
        "• Estrategia de clusters temáticos.\n"
        "• Optimización on-page ilimitada.\n"
        "• Contenido SEO mensual (4 artículos).\n"
        "• Link building ético (5-10 enlaces/mes).\n"
        "• Datos estructurados avanzados.\n"
        "• Optimización para featured snippets.\n"
        "• Análisis de competidores mensual.\n"
        "• Optimización de Core Web Vitals.\n"
        "• Reporte semanal de posiciones.\n"
        "• Reunión quincenal de estrategia.\n"
        "• Gestor SEO dedicado.\n\n"
        "Ideal para: empresas que compiten por keywords "
        "de alto valor.\n\n"
        "Palabras clave: SEO avanzado Colombia, "
        "posicionamiento web profesional, agencia SEO, "
        "link building, SEO técnico avanzado."
    )

    descriptions['Diseño de Logo'] = (
        "Tu logo es la primera impresión de tu marca. "
        "Diseñamos logotipos memorables, versátiles y "
        "profesionales que comunican la esencia de tu "
        "negocio y funcionan en cualquier medio.\n\n"
        "BENEFICIOS:\n\n"
        "• Identidad visual única y memorable.\n"
        "• Versatilidad para cualquier aplicación.\n"
        "• Diferenciación frente a la competencia.\n"
        "• Archivos en todos los formatos necesarios.\n"
        "• Diseño atemporal que perdura.\n"
        "• Guía de uso incluida.\n\n"
        "QUÉ INCLUYE:\n\n"
        "• Briefing de marca y análisis de competencia.\n"
        "• 3 propuestas conceptuales de logotipo.\n"
        "• 3 rondas de revisión y ajustes.\n"
        "• Versiones: principal, horizontal, vertical, "
        "isotipo.\n"
        "• Versiones en positivo, negativo y monocromático.\n"
        "• Archivos: AI, EPS, SVG, PDF, PNG, JPG, WebP.\n"
        "• Paleta de colores con códigos.\n"
        "• Tipografía seleccionada con licencia.\n"
        "• Guía básica de uso del logo.\n\n"
        "PROCESO:\n\n"
        "1. Briefing y research.\n"
        "2. Bocetos y conceptualización.\n"
        "3. Presentación de propuestas.\n"
        "4. Refinamiento del concepto elegido.\n"
        "5. Entrega de archivos finales.\n\n"
        "Palabras clave: diseño de logo Colombia, "
        "logotipo profesional, diseño de marca, crear "
        "logo, diseñador de logos."
    )

    descriptions['Identidad Corporativa'] = (
        "Construye un sistema visual completo que "
        "represente tu empresa en todos los puntos de "
        "contacto. Nuestra Identidad Corporativa va más "
        "allá del logo: es un ecosistema visual coherente "
        "que genera confianza y reconocimiento.\n\n"
        "BENEFICIOS:\n\n"
        "• Coherencia visual en todos los canales.\n"
        "• Profesionalismo en cada interacción.\n"
        "• Guías claras para tu equipo.\n"
        "• Materiales listos para usar.\n"
        "• Mayor recordación de marca.\n"
        "• Base sólida para crecer.\n\n"
        "QUÉ INCLUYE:\n\n"
        "• Diseño de logotipo con variaciones.\n"
        "• Paleta de colores y tipografía.\n"
        "• Manual de identidad (20-30 páginas).\n"
        "• Tarjetas de presentación.\n"
        "• Hoja membretada y sobre.\n"
        "• Firma de correo electrónico.\n"
        "• Carpeta corporativa.\n"
        "• Plantillas para redes sociales.\n"
        "• Presentación corporativa (PPT/Slides).\n"
        "• Favicon y assets web.\n"
        "• Archivos en todos los formatos.\n\n"
        "PROCESO:\n\n"
        "1. Inmersión en la marca.\n"
        "2. Investigación y moodboards.\n"
        "3. Diseño de logotipo.\n"
        "4. Sistema visual completo.\n"
        "5. Aplicaciones y materiales.\n"
        "6. Manual y entrega final.\n\n"
        "Palabras clave: identidad corporativa Colombia, "
        "branding empresarial, imagen corporativa, "
        "manual de marca, diseño de identidad visual."
    )

    descriptions['Diseño de Banner Publicitario'] = (
        "Banners publicitarios de alto impacto visual "
        "para tus campañas digitales. Diseños que capturan "
        "la atención, comunican tu mensaje y generan "
        "clics en Google Display, redes sociales y sitios "
        "web.\n\n"
        "BENEFICIOS:\n\n"
        "• Mayor CTR en tus campañas publicitarias.\n"
        "• Diseño profesional alineado con tu marca.\n"
        "• Múltiples tamaños para cada plataforma.\n"
        "• Entrega rápida (24-48 horas).\n"
        "• Formatos optimizados para web (peso mínimo).\n"
        "• Versiones estáticas y animadas.\n\n"
        "QUÉ INCLUYE:\n\n"
        "• Diseño de banner en hasta 5 tamaños.\n"
        "• Adaptación para Google Display Network.\n"
        "• Adaptación para Facebook/Instagram.\n"
        "• Versión estática (JPG/PNG/WebP).\n"
        "• Versión animada (GIF/HTML5) opcional.\n"
        "• 2 rondas de revisión.\n"
        "• Archivos editables (PSD/AI).\n"
        "• Optimización de peso para carga rápida.\n\n"
        "Palabras clave: diseño de banners Colombia, "
        "banner publicitario, diseño para Google Ads, "
        "creatividades publicitarias, banner digital."
    )

    descriptions['Diseño de Material Gráfico'] = (
        "Material gráfico profesional para comunicar tu "
        "marca en cualquier medio: digital e impreso. "
        "Brochures, flyers, catálogos, presentaciones y "
        "todo lo que tu empresa necesita para destacar.\n\n"
        "BENEFICIOS:\n\n"
        "• Comunicación visual profesional.\n"
        "• Coherencia con tu identidad de marca.\n"
        "• Materiales listos para imprimir y digital.\n"
        "• Diseño orientado a objetivos de comunicación.\n"
        "• Entrega en formatos editables.\n"
        "• Múltiples revisiones incluidas.\n\n"
        "QUÉ INCLUYE:\n\n"
        "• Diseño de la pieza según requerimiento.\n"
        "• Adaptación a tu identidad de marca.\n"
        "• Hasta 3 rondas de revisión.\n"
        "• Archivos para impresión (PDF/X-4, CMYK).\n"
        "• Archivos digitales (PNG, JPG, WebP).\n"
        "• Archivos editables (AI, PSD, INDD).\n\n"
        "TIPOS DE MATERIAL:\n\n"
        "• Brochures y folletos.\n"
        "• Catálogos de productos.\n"
        "• Flyers y volantes.\n"
        "• Presentaciones corporativas.\n"
        "• Infografías.\n"
        "• Tarjetas de presentación.\n"
        "• Papelería corporativa.\n"
        "• Material para ferias y eventos.\n\n"
        "Palabras clave: diseño gráfico Colombia, "
        "material publicitario, diseño de brochure, "
        "diseño de catálogo, material corporativo."
    )

    descriptions['Soporte Técnico por Horas'] = (
        "Soporte técnico especializado bajo demanda, "
        "sin contratos a largo plazo. Compra paquetes de "
        "horas y úsalas cuando necesites resolver "
        "problemas, hacer ajustes o implementar mejoras "
        "en tu sitio web o sistemas.\n\n"
        "BENEFICIOS:\n\n"
        "• Flexibilidad total: usa las horas cuando "
        "quieras.\n"
        "• Sin contratos ni compromisos a largo plazo.\n"
        "• Acceso a equipo técnico especializado.\n"
        "• Resolución rápida de problemas.\n"
        "• Transparencia: reporte detallado de horas.\n"
        "• Costo predecible y controlado.\n\n"
        "QUÉ INCLUYE:\n\n"
        "• Paquetes de 5, 10 o 20 horas.\n"
        "• Corrección de errores y bugs.\n"
        "• Ajustes de diseño y contenido.\n"
        "• Actualizaciones de seguridad.\n"
        "• Instalación de plugins/módulos.\n"
        "• Optimizaciones de rendimiento.\n"
        "• Integraciones menores.\n"
        "• Asesoría técnica.\n"
        "• Reporte detallado de tiempo utilizado.\n"
        "• Horas válidas por 3 meses.\n\n"
        "Palabras clave: soporte técnico web Colombia, "
        "soporte por horas, mantenimiento web por horas, "
        "técnico web, soporte de página web."
    )

    for name, desc in descriptions.items():
        try:
            svc = Service.objects.filter(name=name).first()
            if svc:
                svc.description = desc
                svc.save(update_fields=['description'])
        except Exception:
            pass


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_complete_descriptions'),
    ]

    operations = [
        migrations.RunPython(update_all_descriptions, noop),
    ]
