# Generated by Django 5.2.10 on 2026-02-25 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_clientservice_billing_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientservice',
            name='email_accounts_limit',
            field=models.PositiveIntegerField(default=0, help_text='Aplica para servicios de correo/email. 0 = sin habilitar.', verbose_name='Cuentas de correo habilitadas'),
        ),
        migrations.CreateModel(
            name='ClientEmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='Correo')),
                ('display_name', models.CharField(blank=True, max_length=150, verbose_name='Nombre para mostrar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('client_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to='services.clientservice', verbose_name='Servicio del cliente')),
            ],
            options={
                'verbose_name': 'Cuenta de correo del cliente',
                'verbose_name_plural': 'Cuentas de correo de clientes',
                'ordering': ['email'],
                'unique_together': {('client_service', 'email')},
            },
        ),
    ]
