# Generated by Django 5.2.10 on 2026-02-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_clientservice_email_accounts_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientservice',
            name='auto_disabled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deshabilitado automático'),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='expired_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Notificación de vencido enviada'),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='reminder_15_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Recordatorio 15 días enviado'),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='reminder_3_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Recordatorio 3 días enviado'),
        ),
    ]
