# Generated by Django 5.2.10 on 2026-02-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_clientservice_auto_disabled_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CpanelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_enabled', models.BooleanField(default=False, help_text='Crear/actualizar/eliminar buzones en cPanel al gestionar cuentas.', verbose_name='Sincronizar con cPanel')),
                ('host', models.CharField(blank=True, help_text='Ej: cpanel.tudominio.com', max_length=255, verbose_name='Host cPanel')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Usuario cPanel')),
                ('api_token', models.CharField(blank=True, help_text='Token desde cPanel > Seguridad > API Tokens.', max_length=255, verbose_name='API Token cPanel')),
                ('use_https', models.BooleanField(default=True, verbose_name='Usar HTTPS')),
                ('port', models.PositiveIntegerField(default=2083, verbose_name='Puerto')),
                ('timeout', models.PositiveIntegerField(default=20, verbose_name='Timeout (seg)')),
                ('mailbox_quota_mb', models.PositiveIntegerField(default=2048, verbose_name='Cuota buzón (MB)')),
                ('outlook_imap_host', models.CharField(blank=True, help_text='Servidor entrante para archivos .prf. Vacío = usar host de correo.', max_length=255, verbose_name='IMAP (Outlook)')),
                ('outlook_imap_port', models.PositiveIntegerField(default=993, verbose_name='Puerto IMAP')),
                ('outlook_imap_ssl', models.BooleanField(default=True, verbose_name='IMAP SSL')),
                ('outlook_smtp_host', models.CharField(blank=True, help_text='Servidor saliente para archivos .prf.', max_length=255, verbose_name='SMTP (Outlook)')),
                ('outlook_smtp_port', models.PositiveIntegerField(default=465, verbose_name='Puerto SMTP')),
                ('outlook_smtp_ssl', models.BooleanField(default=True, verbose_name='SMTP SSL')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Configuración cPanel / correo',
                'verbose_name_plural': 'Configuración cPanel / correo',
            },
        ),
    ]
