# Generated by Django 5.2.10 on 2026-02-02 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('invoices', '0001_initial'),
        ('quotes', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaDeCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Número de cuenta de cobro')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagada'), ('overdue', 'Vencida'), ('cancelled', 'Cancelada')], default='pending', max_length=10, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Impuesto')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name='Impuesto (%)')),
                ('issue_date', models.DateField(verbose_name='Fecha de emisión')),
                ('due_date', models.DateField(verbose_name='Fecha de vencimiento')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_de_cobro', to='clients.client', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_de_cobro', to='quotes.quote', verbose_name='Cotización (opcional)')),
            ],
            options={
                'verbose_name': 'Cuenta de cobro',
                'verbose_name_plural': 'Cuentas de cobro',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CuentaDeCobroItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Descripción')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('cuenta_de_cobro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.cuentadecobro', verbose_name='Cuenta de cobro')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Servicio (opcional)')),
            ],
            options={
                'verbose_name': 'Item de cuenta de cobro',
                'verbose_name_plural': 'Items de cuenta de cobro',
                'ordering': ['id'],
            },
        ),
    ]
