# Generated by Django 5.2.10 on 2026-02-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_add_slug_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientservice',
            name='billing_type',
            field=models.CharField(choices=[('unique', 'Pago único'), ('monthly', 'Mensual'), ('annual', 'Anual')], default='monthly', max_length=10, verbose_name='Tipo de precio'),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='renewal_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Si es 0, se asumirá el mismo valor del campo 'Valor'", max_digits=10, verbose_name='Valor renovación'),
        ),
        migrations.AlterField(
            model_name='clientservice',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
    ]
