# Generated by Django 5.2.10 on 2026-02-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_add_user_to_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='document_type',
            field=models.CharField(choices=[('nit', 'NIT (Empresa)'), ('cc', 'Cédula de Ciudadanía'), ('ce', 'Cédula de Extranjería'), ('passport', 'Pasaporte'), ('rtn', 'RTN'), ('other', 'Otro')], default='cc', max_length=10, verbose_name='Tipo de documento'),
        ),
    ]
